#hi. i'm a comment :)

s_up         (rndup[50])                   ?    f_80
f_80         (oport|[80]|[100])            >    t_getpage,f_prnt_80
f_prnt_80    (print|'80 ok: '|)
t_getpage    (getpage)                     ?    f_rcode
f_rcode      (respcf|[200]|)               ?    f_title
f_title      (titlef|'./denied.titles'|-)  ?    f_ctext
f_ctext      (textf|'./denied.words'|-)    ?    f_oopera
f_oopera     (oopera)                      ?    f_prnt_res
f_prnt_res   (print|'found: '|)
